print("Badrul munir")
print("312210403")

# Luas dan keliling lingkaran
d = float(input(" masukan diameter lingkaran : "))
r = (d/2)
phi = 3.14
L = phi * (r * r)
K = (phi * d)
print(" diketahui : ")
print("diameter = ",d,"cm")
print(" jari-jari = ",r,"cm")
print(" phi = ",phi)
print(" dintanya luas lingkaran dan keliling lingkaran ?")
print(" L = phi x r x r ")
print(" L = ",phi," x ",r," x ",r)
print(" k = phi x d")
print(" k = ",phi," x ",d)
print(" Luas lingkaran adalah = ",L,"cm")
print(" keliling Lingkaran adalah = ",K,"cm")